package com.jtarun.practice.leetcode;


/** 389
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 */
public class FindDifferenceChar {
    class Solution {
        public char findTheDifference(String s, String t) {
            int n = s.length();

            int x = 0;
            for (int i = 0; i < n; i++) {
                x ^= s.charAt(i) - '\0';
                x ^= t.charAt(i) - '\0';
            }

            x ^= t.charAt(n) - '\0';

            return (char)x;
        }
    }

}
